export type QuoteSeed = {
  body: string;
  author: string;
  category: "mindset" | "fitness" | "disciplina" | "nutricion";
};

export const QUOTE_SEED: QuoteSeed[] = [
  { body: "El dolor que sientes hoy será la fuerza que sientas mañana.", author: "Arnold Schwarzenegger", category: "fitness" },
  { body: "No cuentas los días, haces que los días cuenten.", author: "Muhammad Ali", category: "disciplina" },
  { body: "Tu cuerpo puede soportar casi cualquier cosa. Convence a tu mente.", author: "David Goggins", category: "mindset" },
  { body: "Disciplina es elegir entre lo que quieres ahora y lo que quieres más.", author: "Abraham Lincoln", category: "disciplina" },
  { body: "Un pequeño progreso cada día suma grandes resultados.", author: "Satya Nani", category: "mindset" },
  { body: "No te entrenas para verte bien, te entrenas para no rendirte nunca.", author: "Vitalis", category: "fitness" },
  { body: "La motivación te arranca, el hábito te mantiene en marcha.", author: "Jim Ryun", category: "disciplina" },
  { body: "Sudar es la inversión más rentable que existe.", author: "Vitalis", category: "fitness" },
  { body: "Cuida tu cuerpo: es el único lugar donde tienes que vivir.", author: "Jim Rohn", category: "nutricion" },
  { body: "Eres una obra maestra en construcción, no un borrador.", author: "Vitalis", category: "mindset" },
  { body: "La consistencia es lo que transforma lo ordinario en extraordinario.", author: "Vitalis", category: "disciplina" },
  { body: "Compite con quien fuiste ayer, no con quien es otro hoy.", author: "Vitalis", category: "mindset" },
  { body: "Los músculos se rompen en el gimnasio, se construyen en la cocina.", author: "Vitalis", category: "nutricion" },
  { body: "Si duele, es porque estás cambiando.", author: "Vitalis", category: "fitness" },
  { body: "Nadie llegó lejos dejando de intentarlo cada día.", author: "Vitalis", category: "disciplina" },
  { body: "La energía que no gastas en excusas la recuperas en resultados.", author: "Vitalis", category: "mindset" },
  { body: "Cada comida es una decisión: ¿construyes o destruyes?", author: "Vitalis", category: "nutricion" },
  { body: "Levántate, muévete, repite. Ese es todo el secreto.", author: "Vitalis", category: "fitness" },
  { body: "El éxito es la suma de pequeños esfuerzos repetidos en el tiempo.", author: "Robert Collier", category: "disciplina" },
  { body: "No esperes el momento perfecto, haz perfecto el momento.", author: "Vitalis", category: "mindset" },
  { body: "Tu récord de mañana empieza con la serie de hoy.", author: "Vitalis", category: "fitness" },
  { body: "Descansar también es entrenar.", author: "Vitalis", category: "nutricion" },
  { body: "La versión de ti que quieres ser ya existe: sal a buscarla.", author: "Vitalis", category: "mindset" },
  { body: "La voluntad es un músculo: entrénala como cualquier otro.", author: "Vitalis", category: "disciplina" },
  { body: "Bebe agua, duerme profundo, vuelve más fuerte.", author: "Vitalis", category: "nutricion" },
  { body: "Un 1% mejor cada día te vuelve irreconocible en un año.", author: "James Clear", category: "disciplina" },
  { body: "Las excusas no queman calorías.", author: "Vitalis", category: "fitness" },
  { body: "No hay atajos, hay mañanas.", author: "Vitalis", category: "disciplina" },
  { body: "Tu mente abandona mil veces antes que tu cuerpo. Escucha al cuerpo.", author: "Vitalis", category: "mindset" },
  { body: "Construye hábitos que te defiendan cuando falte la motivación.", author: "Vitalis", category: "disciplina" },
  { body: "Nadie ha lamentado nunca el entrenamiento que sí hizo.", author: "Vitalis", category: "fitness" },
  { body: "Si esperas a tener ganas, no empezarás nunca. Empieza y las ganas llegan.", author: "Vitalis", category: "disciplina" },
  { body: "El cuerpo logra lo que la mente cree.", author: "Napoleon Hill", category: "mindset" },
  { body: "No se trata de tener tiempo, se trata de hacer tiempo.", author: "Vitalis", category: "disciplina" },
  { body: "Come para rendir, no solo para llenarte.", author: "Vitalis", category: "nutricion" },
  { body: "La fuerza no viene de lo que puedes hacer, sino de superar lo que creías imposible.", author: "Rikki Rogers", category: "mindset" },
  { body: "Hoy haz algo por lo que tu yo de mañana te dé las gracias.", author: "Vitalis", category: "disciplina" },
  { body: "La proteína construye, el descanso repara, la constancia transforma.", author: "Vitalis", category: "nutricion" },
  { body: "Cada repetición extra es un voto a favor de la persona que quieres ser.", author: "James Clear", category: "disciplina" },
  { body: "El gimnasio no cambia tu cuerpo, cambia tu carácter. El cuerpo viene después.", author: "Vitalis", category: "mindset" },
  { body: "Entrena como si fueras el segundo. Descansa como si fueras el primero.", author: "Vitalis", category: "fitness" },
  { body: "El azúcar da placer cinco minutos. La energía estable dura todo el día.", author: "Vitalis", category: "nutricion" },
  { body: "No necesitas ser extremo, solo necesitas ser constante.", author: "Vitalis", category: "disciplina" },
  { body: "Duele ahora y sé un campeón, o rindete ahora y sé un cobarde.", author: "Muhammad Ali", category: "fitness" },
  { body: "Tus excusas son solo mentiras bien vestidas.", author: "Vitalis", category: "mindset" },
  { body: "Hidratarte bien es el truco de rendimiento más barato que existe.", author: "Vitalis", category: "nutricion" },
  { body: "La motivación es lo que te pone en marcha. El hábito es lo que te mantiene.", author: "Jim Rohn", category: "disciplina" },
  { body: "El progreso lento sigue siendo progreso. El abandono no.", author: "Vitalis", category: "mindset" },
  { body: "Si quieres resultados distintos, deja de negociar contigo mismo cada mañana.", author: "Vitalis", category: "disciplina" },
  { body: "Lo que comes en privado se ve en público.", author: "Vitalis", category: "nutricion" },
  { body: "El límite no es el cielo, el límite eres tú.", author: "Vitalis", category: "mindset" },
  { body: "Un buen entrenamiento no se mide en sudor, se mide en técnica.", author: "Vitalis", category: "fitness" },
  { body: "Dormir mal es entrenar con el freno de mano puesto.", author: "Vitalis", category: "nutricion" },
  { body: "No cuentes las repeticiones, haz que cada repetición cuente.", author: "Vitalis", category: "fitness" },
  { body: "La diferencia entre querer y lograr se llama rutina.", author: "Vitalis", category: "disciplina" },
  { body: "Tu peor entrenamiento es infinitamente mejor que el que no hiciste.", author: "Vitalis", category: "fitness" },
  { body: "Invierte en tu salud ahora o pagarás en enfermedad después.", author: "Vitalis", category: "nutricion" },
  { body: "El dolor es temporal. Rendirse dura para siempre.", author: "Lance Armstrong", category: "mindset" },
  { body: "No busques motivación, construye sistemas que no dependan de ella.", author: "Vitalis", category: "disciplina" },
  { body: "El mejor momento para empezar fue hace un año. El segundo mejor es hoy.", author: "Proverbio chino", category: "mindset" },
  { body: "Cuida tu descanso con la misma obsesión que cuidas tus series.", author: "Vitalis", category: "nutricion" },
  { body: "Cada día que entrenas le ganas terreno a tu versión mediocre.", author: "Vitalis", category: "fitness" },
  { body: "La disciplina pesa gramos. El arrepentimiento pesa toneladas.", author: "Jim Rohn", category: "disciplina" },
  { body: "Respira. Aprieta. Suelta. Repite. Así se construye un cuerpo fuerte.", author: "Vitalis", category: "fitness" },
  { body: "Tu mente se rinde antes que tus piernas. Recuérdalo en la última serie.", author: "Vitalis", category: "mindset" },
];

export const HABIT_PRESETS: {
  title: string;
  icon: string;
  color: string;
}[] = [
  { title: "Entrenar 45 min", icon: "🏋️", color: "violet" },
  { title: "Beber 3L de agua", icon: "💧", color: "cyan" },
  { title: "Comer comida real", icon: "🥗", color: "lime" },
  { title: "Dormir 8 horas", icon: "😴", color: "amber" },
  { title: "Leer 10 páginas", icon: "📚", color: "rose" },
];
